medical_claim/urls.py
from django.urls import path
from . import views

app_name = "medical"

urlpatterns = [
    path('dashboard/', views.medical_dashboard, name='dashboard'),
    path('submit/', views.medical_submit, name='submit'),
    path('delete/<int:claim_id>', views.claim_delete, name='delete'),
    path('detail/<int:claim_id>', views.medical_detail, name='detail'),
    path('history/', views.medical_history, name='history'),
    path('history/<int:year>', views.medical_history_dashboard, name='history_dashboard'),
]

mitasa/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from user.views import login_view as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', login, name='index'),
    path('', include('helper.urls')),
    path('user/', include('user.urls')),
    path('claim/', include('claim.urls')),
    path('staff/', include('mitasa_admin.urls')),
    path('medical/', include('medical_claim.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile_view, name="profile"),
    path('profile/new', views.profile_new, name="profile_new"),
    path('profile/edit', views.user_edit, name="edit"),
    path('profile/details/edit', views.profile_edit, name="profile_edit"),
    path('password/change', views.password_change, name="password_change"),
]

medical_claim/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Sum
from claim.models import Claim_Status
import datetime

YEARLY_LIMIT = 3000

BENEFICIERY_CHOICES = [
    ("Myself", "Myself"),
    ("Husband", "Husband"),
    ("Children", "Children")
]

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.claimer.id, filename)

# File path of receipt files
def claim_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.claim.claimer.id, filename)

class Medical_Claim(models.Model):
    claimer = models.ForeignKey(User, on_delete=models.CASCADE)
    beneficier = models.CharField(choices=BENEFICIERY_CHOICES, max_length=100)
    amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    file = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    claim_year = models.IntegerField(default=datetime.datetime.now().year)
    claim_status = models.ForeignKey(Claim_Status, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def clean(self):
        current_year = timezone.now().year

        pending_claims = Medical_Claim.objects.filter(
            claimer=self.claimer_id,
            claim_status=1,
            created_at__year= current_year
        ).aggregate(total_amount=Sum('amount'))['total_amount'] or 0

        approved_claims = Medical_Claim.objects.filter(
            claimer=self.claimer_id,
            claim_status=2,
            created_at__year= current_year
        ).aggregate(total_amount=Sum('amount'))['total_amount'] or 0

        total_claimed = approved_claims

        if total_claimed + self.amount > YEARLY_LIMIT:
            raise ValidationError(f'You have exceeded your claim limit for the year. Yearly Limit: RM{YEARLY_LIMIT}, Total claimed: RM{total_claimed}, Attempted claim: RM{self.amount}')

    def save(self, *args, **kwargs):
        self.clean()  # Call the clean method to perform validation
        super().save(*args, **kwargs)

class Approved_Medical_Claim(models.Model):
    claim = models.OneToOneField(Medical_Claim, primary_key=True, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    receipt = models.FileField(upload_to=claim_directory_path, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Claimer: {self.claim.claimer.username} | Approved At: {self.created_at}'
    
class Rejected_Medical_Claim(models.Model):
    claim = models.OneToOneField(Medical_Claim, primary_key=True, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Claimer: {self.claim.claimer.username} | Approved At: {self.created_at}'

medical_claim/forms.py
from django import forms
from .models import Medical_Claim, Approved_Medical_Claim, Rejected_Medical_Claim

class MedicalClaimForm(forms.ModelForm):
    class Meta:
        model = Medical_Claim
        fields = ["amount","beneficier", "file"]

class ApproveMedicalForm(forms.ModelForm):
    class Meta:
        model = Approved_Medical_Claim
        fields = ["amount", "receipt"]

class RejectMedicalForm(forms.ModelForm):
    class Meta:
        model = Rejected_Medical_Claim
        fields = ["reason"]

medical_claim/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from django.urls import reverse
from .models import Medical_Claim
from django.db.models import Sum, Count
from django.core.exceptions import ValidationError
from claim.models import Claim_Status
from .models import Medical_Claim
from .forms import MedicalClaimForm, ApproveMedicalForm, RejectMedicalForm
from .models import YEARLY_LIMIT as YEARLY_CLAIM_LIMIT
import math
import datetime

# Create your views here.

def medical_dashboard(request):
    current_year = datetime.datetime.now().year

    claims = Medical_Claim.objects.filter(claimer=request.user, claim_year=current_year)
    pending_claims = claims.filter(claim_status=1)
    approved_claims = claims.filter(claim_status=2)
    rejected_claims = claims.filter(claim_status=3)

    pending_amount = pending_claims.aggregate(Sum("amount"))["amount__sum"] or 0
    approved_amount = approved_claims.aggregate(Sum("approved_medical_claim__amount"))["approved_medical_claim__amount__sum"] or 0

    yearly_limit = YEARLY_CLAIM_LIMIT
    claim_limit = yearly_limit - (pending_amount + approved_amount)

    claim_limit_percentage = 100 - math.ceil(claim_limit / yearly_limit * 100)

    context = {
        'yearly_limit': yearly_limit,
        'claim_limit': claim_limit,
        'pending_claims': pending_claims,
        'approved_claims': approved_claims,
        'rejected_claims': rejected_claims,
        'pending_amount': pending_amount,
        'approved_amount': approved_amount,
        'claim_limit_percentage': claim_limit_percentage
    }
    return render(request, 'medical_claim/medical_dashboard.html', context)

def medical_submit(request):
    if not request.user.is_authenticated:
        return HttpResponse("User is not authenticated", status=401)  # Ensure the user is authenticated
    
    if request.method == 'POST':
        form = MedicalClaimForm(request.POST, request.FILES)
        if form.is_bound:  # Check if form is bound
            claim = form.save(commit=False)
            claim.claimer = request.user  # Set the claimer before validation
            form.instance = claim  # Update the form's instance

            if form.is_valid():
                try:
                    claim_status, created = Claim_Status.objects.get_or_create(status="Pending")
                    claim.claim_status = claim_status
                    claim.save()
                    return HttpResponseRedirect(reverse('medical:dashboard'))
                except ValidationError as e:
                    form.add_error(None, e)
    else:
        form = MedicalClaimForm()

    context = {
        'form': form
    }
    return render(request, 'medical_claim/medical_submit.html', context)

def medical_detail(request, claim_id):
    claim = Medical_Claim.objects.get(pk=claim_id)

    is_Pending = False
    is_Approved = False
    is_Rejected = False

    if claim.claim_status.id == 1:
        is_Pending = True
    if claim.claim_status.id == 2:
        is_Approved = True
    if claim.claim_status.id == 3:
        is_Rejected = True

    is_admin = False
    if request.user.is_staff:
        is_admin = True

    approveForm = ApproveMedicalForm(prefix="approved")
    rejectForm = RejectMedicalForm(prefix="rejected")

    if request.method == 'POST':
        if 'approve' in request.POST:
            approveForm = ApproveMedicalForm(request.POST, request.FILES, prefix="approved")
            if approveForm.is_valid():
                instance = approveForm.save(commit=False)
                instance.claim = claim
                claim_status, created = Claim_Status.objects.get_or_create(status="Approved")
                claim.claim_status = claim_status
                claim.save()
                instance.save()
                return redirect('mitasa_admin:medical_dashboard')
        elif 'reject' in request.POST:
            rejectForm = RejectMedicalForm(request.POST, prefix="rejected")
            if rejectForm.is_valid():
                instance = rejectForm.save(commit=False)
                instance.claim = claim
                claim_status, created = Claim_Status.objects.get_or_create(status="Rejected")
                claim.claim_status = claim_status
                claim.save()
                instance.save()
                return redirect('mitasa_admin:medical_dashboard')
        else:
            approveForm = ApproveMedicalForm(prefix="approved")
            rejectForm = RejectMedicalForm(prefix="rejected")

    context = {
        'claim': claim,

        'is_Pending': is_Pending,
        'is_Approved': is_Approved,
        'is_Rejected': is_Rejected,

        'is_admin': is_admin,

        'approveForm': approveForm,
        'rejectForm': rejectForm,
    }
    return render(request, 'medical_claim/medical_detail.html', context)

def medical_history(request):
    claims = Medical_Claim.objects.filter(claimer=request.user)

    claims_by_year_list = claims.values('claim_year').annotate(total_claims=Count('id')).annotate(total_approved_claims=Count('approved_medical_claim__claim_id')).annotate(total_approved_amount=Sum('approved_medical_claim__amount')).order_by('claim_year')

    overall_claims = 0
    overall_approved_claims = 0
    overall_approved_amount = 0

    for claim in claims_by_year_list:
        overall_claims += (claim['total_claims']) or 0
        overall_approved_claims += (claim['total_approved_claims']) or 0
        overall_approved_amount += (claim['total_approved_amount']) or 0

    context = {
        'claims_by_year_list': claims_by_year_list,
        'overall_claims': overall_claims,
        'overall_approved_claims': overall_approved_claims,
        'overall_approved_amount': overall_approved_amount,
    }

    return render(request, 'medical_claim/medical_history.html', context)

def medical_history_dashboard(request, year):
    claims = Medical_Claim.objects.filter(claimer=request.user, claim_year=year)
    pending_claims = claims.filter(claim_status=1)
    approved_claims = claims.filter(claim_status=2)
    rejected_claims = claims.filter(claim_status=3)

    approved_amount = approved_claims.aggregate(Sum("approved_medical_claim__amount"))["approved_medical_claim__amount__sum"] or 0

    context = {
        'year': year,
        'claims': claims,
        'pending_claims': pending_claims,  
        'approved_claims': approved_claims,  
        'rejected_claims': rejected_claims,
        'approved_amount': approved_amount,
    }

    return render(request, 'medical_claim/medical_history_dashboard.html', context)

def claim_delete(request, claim_id):
    if request.method == 'POST':
        claim = Medical_Claim.objects.get(pk=claim_id)
        claim.delete()
    
    return HttpResponseRedirect(reverse('medical:dashboard'))

medical_claim/templates/medical_claim/medical_dashboard.html
{% extends "dashboard.html" %}
{% block nav_medical_claims %}active{% endblock nav_medical_claims %}
{% block page_title %}
    <span class="text-primary">Medical Dashboard</span> | {{ block.super }}
{% endblock page_title %}
{% block button_1 %}<a class="btn btn-outline-warning" href="{% url 'medical:history' %}" data-mdb-ripple-init data-mdb-ripple-color="dark">Medical Claim History <i class="fas fa-clock-rotate-left"></i></a>{% endblock button_1 %}
{% block cards %}
    {% block card_claim_limit %}
        <div class="card-group">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title text-center">Medical Claim Limit</h5>
                    <hr class="hr">
                    <div class="progress" style="height: 20px;">
                        <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
                            role="progressbar"
                            style="width: {{ claim_limit_percentage }}%"
                            aria-valuenow="{{ claim_limit_percentage }}"
                            aria-valuemin="0"
                            aria-valuemax="100">{{ claim_limit_percentage }}%</div>
                    </div>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title text-center text-info">Medical Claim Remaining</h5>
                    <hr class="hr">
                    <p class="text-center lead">RM {{ claim_limit }} <span class="text-danger">/ {{ yearly_limit }}</span></p>
                </div>
            </div>
        </div>
    {% endblock card_claim_limit %}
    {{ block.super }}
{% endblock cards %}
{% block card_pending %}
    {{ pending_claims|length }}
{% endblock card_pending %}
{% block card_pending_amount %}
    {{ pending_amount }}
{% endblock card_pending_amount %}
{% block card_approved %}
    {{ approved_claims|length }}
{% endblock card_approved %}
{% block card_approved_amount %}
    {{ approved_amount }}
{% endblock card_approved_amount %}
{% block dashboard_content %}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Pending Claims</h2>
        <div class="align-self-center">
            {% block button_2 %}<a class="btn btn-primary" href="{% url 'medical:submit' %}" data-mdb-ripple-init>Add Medical Claim <i class="fas fa-plus"></i></a>{% endblock button_2 %} 
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">List of Medical Claims</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Claim ID</th>
                            {% if admin_view %}<th scope="col">Name</th>{% endif %}
                            <th scope="col">Created At</th>
                            <th scope="col">Amount (RM)</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for claim in pending_claims %}
                            <tr>
                                <td>
                                    <a href="{% url 'medical:detail' claim.id %}">#{{ claim.id }}</a>
                                </td>
                                {% if admin_view %}<td>{{ claim.claimer.first_name }}</td>{% endif %}
                                <td>{{ claim.created_at }}</td>
                                <td>{{ claim.amount }}</td>
                                <td>
                                    <span class="badge bg-warning">{{ claim.claim_status }}</span>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5">No medical claims found.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <hr class="hr">
    <h3 class="mb-3">Approved Claims</h3>
    <div class="card mb-3">
        <div class="card-header">List of Medical Claims</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Claim ID</th>
                            {% if admin_view %}<th scope="col">Name</th>{% endif %}
                            <th scope="col">Approved At</th>
                            <th scope="col">Amount (RM)</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for claim in approved_claims %}
                            <tr>
                                <td>
                                    <a href="{% url 'medical:detail' claim.id %}">#{{ claim.id }}</a>
                                </td>
                                {% if admin_view %}<td>{{ claim.claimer.first_name }}</td>{% endif %}
                                <td>{{ claim.created_at }}</td>
                                <td>{{ claim.approved_medical_claim.amount }}</td>
                                <td>
                                    <span class="badge bg-success">{{ claim.claim_status }}</span>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5">No medical claims found.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <hr class="hr">
    <h3 class="mb-3">Rejected Claims</h3>
    <div class="card mb-3">
        <div class="card-header">List of Medical Claims</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Claim ID</th>
                            {% if admin_view %}<th scope="col">Name</th>{% endif %}
                            <th scope="col">Created At</th>
                            <th scope="col">Amount (RM)</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for claim in rejected_claims %}
                            <tr>
                                <td>
                                    <a href="{% url 'medical:detail' claim.id %}">#{{ claim.id }}</a>
                                </td>
                                {% if admin_view %}<td>{{ claim.claimer.first_name }}</td>{% endif %}
                                <td>{{ claim.created_at }}</td>
                                <td>{{ claim.amount }}</td>
                                <td>
                                    <span class="badge bg-danger">{{ claim.claim_status }}</span>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5">No medical claims found.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock dashboard_content %}

medical_claim/templates/medical_claim/medical_detail.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-4">
        <h1>Medical Claim Detail</h1>
        <hr class="hr">
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Staff ID:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.claimer.username }}</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Name:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.claimer.first_name }} {{ claim.claimer.last_name }}</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Email:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.claimer.email }}</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Bank:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.claimer.profile.bank_name }}</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Account Number:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.claimer.profile.account_number }}</p>
            </div>
        </div>
        <hr class="hr">
        <h2>Medical Claim: #{{ claim.id }}</h2>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Claim Beneficier:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.beneficier }}</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Claim Date:</p>
            <div class="col-sm-10">
                <p class="form-control-plaintext">{{ claim.created_at }} ({{ claim.created_at|timesince }} ago)</p>
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">File:</p>
            <div class="col-sm-3">
                {% if claim.file %}
                    <i class="fa-regular fa-file"></i> <a href="{% url 'claim:download' claim.file.name %}">Download File</a>
                {% else %}
                    <p class="form-control-plaintext">No file available</p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <p class="col-sm-2 col-form-label bold-small">Total Medical Claim:</p>
            <div class="col-sm-3">
                <p class="form-control-plaintext">RM{{ claim.amount }}</p>
            </div>
        </div>
        <hr class="hr">
        {% if is_Pending %}
            <div class="row mb-2">
                <p class="col-sm-2 col-form-label bold-small">Status:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext">
                        <span class="badge bg-warning">PENDING</span>
                    </p>
                </div>
            </div>
            {% if request.user == claim.claimer %}
                <button type="button"
                        class="btn btn-danger"
                        data-mdb-modal-init
                        data-bs-target="#delete{{ claim.id }}">
                    <i class="fa-solid fa-trash-can fa-lg"></i>
                </button>
                <div class="modal"
                    id="delete{{ claim.id }}"
                    tabindex="-1"
                    aria-labelledby="myModalLabel2"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">
                                    Medical Claim ID: {{ claim.id }}
                                    <br />
                                    Claim Date: {{ claim.created_at }}
                                </h5>
                                <button type="button"
                                        class="btn-close"
                                        data-bs-dismiss="modal"
                                        aria-label="Close">
                                    <span aria-hidden="true"></span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Are you sure you want to delete this claim?</p>
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'medical:delete' claim.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary" value="Delete" />
                                </form>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if request.user.is_staff %}
                <button type="button"
                        class="btn btn-success"
                        data-mdb-modal-init
                        data-mdb-target="#approve{{ claim.id }}">Approve</button>
                <button type="button"
                        class="btn btn-danger"
                        data-mdb-modal-init
                        data-mdb-target="#reject{{ claim.id }}">Reject</button>
            {% endif %}
        {% elif is_Approved %}
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Status:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext">
                        <span class="badge bg-success">APPROVED</span>
                    </p>
                </div>
            </div>
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Approval Date:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext">{{ claim.approved_medical_claim.created_at }}</p>
                </div>
            </div>
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Receipt:</p>
                <div class="col-sm-3">
                    {% if claim.approved_medical_claim.receipt %}
                        <p class="form-control-plaintext">
                            <i class="fa-regular fa-file"></i> <a href="{% url 'claim:download' claim.approved_medical_claim.receipt.name %}">Download Receipt</a>
                        </p>
                    {% else %}
                        <p class="form-control-plaintext">No file available</p>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Approved Amount:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext bold-small">RM{{ claim.approved_medical_claim.amount }}</p>
                </div>
            </div>
        {% elif is_Rejected %}
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Status:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext">
                        <span class="badge bg-danger">REJECTED</span>
                    </p>
                </div>
            </div>
            <div class="row">
                <p class="col-sm-2 col-form-label bold-small">Reason:</p>
                <div class="col-sm-3">
                    <p class="form-control-plaintext">{{ claim.rejected_medical_claim.reason }}</p>
                </div>
            </div>
        {% endif %}
        <a href="{{ request.META.HTTP_REFERER }}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a>
    </div>
    <!--Approve Modal-->
    <div class="modal fade"
         id="approve{{ claim.id }}"
         tabindex="-1"
         aria-labelledby="myModalLabel2"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        Claim ID: {{ claim.id }}
                        <br />
                        Program Name: {{ claim.program_name }}
                    </h5>
                    <button type="button"
                            class="btn-close"
                            data-mdb-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <form action="{% url 'medical:detail' claim.id %}"
                              method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ approveForm|crispy }}
                            <button name="approve" type="submit" class="btn btn-primary">Approve</button>
                            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Cancel</button>
                        </form>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
    <!--Reject Modal-->
    <div class="modal fade"
         id="reject{{ claim.id }}"
         tabindex="-1"
         aria-labelledby="myModalLabel2"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">
                        Claim ID: {{ claim.id }}
                        <br />
                    </h5>
                    <button type="button"
                            class="btn-close"
                            data-mdb-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <form action="{% url 'medical:detail' claim.id %}"
                              method="post">
                            {% csrf_token %}
                            {{ rejectForm|crispy }}
                            <button name="reject" type="submit" class="btn btn-danger">Reject</button>
                            <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Cancel</button>
                        </form>
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
{% endblock content %}

medical_claim/templates/medical_claim/medical_history.html
{% extends "history.html" %}
{% block page_title %}<span class="text-danger">Medical History</span> | {{ block.super }}{% endblock page_title %}
{% block back_link %}{% url 'medical:dashboard' %}{% endblock back_link %}
{% block view_link %}{% url 'medical:history_dashboard' claim.claim_year %}{% endblock view_link %}