claim/urls.py
from django.urls import path
from . import views

app_name = "claim"

urlpatterns = [
    path('dashboard/', views.claim_dashboard, name="dashboard"),
    path('submit/', views.claim_submit, name="submit"),
    path('detail/<int:claim_id>', views.claim_detail, name="detail"),
    path('delete/<int:claim_id>', views.claim_delete, name="delete"),
    path('history/', views.claim_history, name="history"),
    path('history/<int:year>', views.history_dashboard, name="history_dashboard"),
]

mitasa/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from user.views import login_view as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', login, name='index'),
    path('', include('helper.urls')),
    path('user/', include('user.urls')),
    path('claim/', include('claim.urls')),
    path('staff/', include('mitasa_admin.urls')),
    path('medical/', include('medical_claim.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile_view, name="profile"),
    path('profile/new', views.profile_new, name="profile_new"),
    path('profile/edit', views.user_edit, name="edit"),
    path('profile/details/edit', views.profile_edit, name="profile_edit"),
    path('password/change', views.password_change, name="password_change"),
]

claim/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import datetime

# File path of files uploaded during claim submission.
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.claimer.id, filename)

# File path of receipt files
def claim_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.claim.claimer.id, filename)

class Claim_Status(models.Model):
    status = models.CharField(max_length=10)
    
    def __str__(self):
        return self.status

class Claim(models.Model):
    accommodation_choices = [
        (0, "Online"),  
        (1, "Provided"),
        (2, "Not provided"),
    ]

    meal_choices = [
        (0, ""),
        (1, "Provided"),
        (2, "Not provided")
    ]

    month_choices = [(1, "January"),
                     (2, "February"),
                     (3, "March"),
                     (4, "April"),
                     (5, "May"),
                     (6, "June"),
                     (7, "July"),
                     (8, "August"),
                     (9, "September"),
                     (10, "October"),
                     (11, "November"),
                     (12, "December"),]
    
    mode_choices = [
        ("", ""),
        ("Online", "Online"),
        ("Physical", "Physical")
    ]
    
    claimer = models.ForeignKey(User, on_delete=models.CASCADE)
    program_name = models.CharField(max_length=200)
    program_start_date = models.DateTimeField()
    program_end_date = models.DateTimeField()
    program_mode = models.CharField(choices=mode_choices, max_length=10, default="")
    program_location = models.TextField()
    program_letter_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    claim_month = models.IntegerField(choices=month_choices, default=0)
    claim_year = models.IntegerField(default=datetime.datetime.now().year)

    work_hours = models.IntegerField(default=0)
    work_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)

    travel_distance = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    travel_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    travel_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    accommodation_choice = models.IntegerField(choices=accommodation_choices, default=0)
    accommodation_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    accommodation_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    meal_choice = models.IntegerField(choices=meal_choices, default=0)
    meal_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    meal_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    toll_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    toll_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    parking_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    parking_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    plane_ticket_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    plane_ticket_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    other_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    other_file = models.FileField(upload_to=user_directory_path, null=True, blank=True)

    total_amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)
    claim_status = models.ForeignKey(Claim_Status, on_delete=models.SET_NULL, null=True)

    def clean(self):
        # Check if any existing claims have the same program start and end dates for the same claimer
        if Claim.objects.filter(
            claimer=self.claimer_id,
            program_start_date=self.program_start_date,
            program_end_date=self.program_end_date
        ).exclude(pk=self.pk).exists():
            raise ValidationError("A claim for the same program dates and times already exists.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Claimer: {self.claimer.username} | Program Name: {self.program_name} | Created At: {self.created_at}'
    
class Approved_Claim(models.Model):
    claim = models.OneToOneField(Claim, primary_key=True, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    receipt = models.FileField(upload_to=claim_directory_path, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Claimer: {self.claim.claimer.username} | Program Name: {self.claim.program_name} | Approved At: {self.created_at}'
    
class Rejected_Claim(models.Model):
    claim = models.OneToOneField(Claim, primary_key=True, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Claimer: {self.claim.claimer.username} | Program Name: {self.claim.program_name} | Approved At: {self.created_at}'

claim/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from .models import Claim, Claim_Status, Approved_Claim, Rejected_Claim
from .forms import ClaimForm, ApproveForm, RejectForm
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db.models import Sum, Count
from django.http import Http404
import datetime

# Constants
MONTH_NAMES = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}

ACCOMMODATION_CHOICE = {
    0: 'Online',
    1: 'Provided',
    2: 'Not provided'
}

MEAL_CHOICE = {
    0: 'Online',
    1: 'Provided',
    2: 'Not provided',
}

# Long work hours > 8 hours
SHORT_WORK_HOURS = 4
SHORT_WORK_AMOUNT = 50.0
LONG_WORK_AMOUNT = 100.0 
SHORT_MEAL_AMOUNT = 30.0
LONG_MEAL_AMOUNT = 60.0

# Methods
def calculate_amounts(user, claim):
    # Work hours calculation
    date_1 = claim.program_start_date
    date_2 = claim.program_end_date

    diff = date_2 - date_1

    days, seconds = diff.days, diff.seconds
    hours = days * 24 + seconds // 3600

    claim.work_hours = hours

    work_hours = divmod(hours, 24)

    # Check if user is staff
    is_staff = user.groups.filter(name="Staff").exists()

    #Exco's calculation
    if claim.program_mode == "Online":
        claim.work_amount = SHORT_WORK_AMOUNT
        claim.meal_amount = 0

    if claim.program_mode == "Physical":
        if hours <= SHORT_WORK_HOURS:
            claim.work_amount = SHORT_WORK_AMOUNT

            if claim.meal_choice == 2:
                claim.meal_amount = 30
        else:
            # Work Allowance Calculation
            claim.work_amount = LONG_WORK_AMOUNT * work_hours[0]
            if work_hours[1] <= SHORT_WORK_HOURS:
                claim.work_amount += SHORT_WORK_AMOUNT
            else:
                claim.work_amount += LONG_WORK_AMOUNT

            # Meal Allowance Calculatioon
            if claim.meal_choice == 2:
                claim.meal_amount = (LONG_MEAL_AMOUNT * work_hours[0])
                if work_hours[1] <= SHORT_WORK_HOURS:
                    claim.meal_amount += SHORT_MEAL_AMOUNT
                else:
                    claim.meal_amount += LONG_MEAL_AMOUNT

    # Travel amount calculations
    claim.travel_amount = float(claim.travel_distance) * 0.80
    
    claim.total_amount = (
        float(claim.work_amount) +
        float(claim.travel_amount) +
        float(claim.accommodation_amount) +
        float(claim.meal_amount) +
        float(claim.toll_amount) +
        float(claim.parking_amount) +
        float(claim.plane_ticket_amount) +
        float(claim.other_amount)
    )

# View functions
def claim_dashboard(request):
    current_year = datetime.datetime.now().year
    claims = Claim.objects.filter(claimer=request.user.id, claim_year=current_year)

    pending_claims = claims.filter(claim_status=1)
    approved_claims = claims.filter(claim_status=2, claim_year=current_year)
    rejected_claims = claims.filter(claim_status=3, claim_year=current_year)

    approved_claims_obj = Approved_Claim.objects.filter(claim__in=approved_claims)

    # Total claims
    pending_claims_count = pending_claims.count()
    approved_claims_count = approved_claims.count()
    rejected_claims_count = rejected_claims.count()

    # Claims by month initialization
    pending_claims_by_month = {month: [] for month in range(1, 13)}
    approved_claims_by_month = {month: [] for month in range(1, 13)}

    total_pending_amount_by_month = {month: [] for month in range(1, 13)}
    total_approved_amount_by_month = {month: [] for month in range(1, 13)}

    # Retrieve claims and organize them by month and status
    for month in range(1, 13):
        month_pending_claims = pending_claims.filter(claim_month=month, claim_year=current_year)
        month_approved_claims = approved_claims.filter(claim_month=month, claim_year=current_year)

        pending_claims_by_month[month] = list(month_pending_claims)
        approved_claims_by_month[month] = list(month_approved_claims)

        total_pending_amount_by_month[month] = month_pending_claims.aggregate(Sum('total_amount'))['total_amount__sum'] or 0
        total_approved_amount_by_month[month] = approved_claims_obj.filter(claim__in=month_approved_claims).aggregate(Sum('amount'))['amount__sum'] or 0

    # Total amount 
    total_pending_amount = claims.filter(claim_status=1).aggregate(Sum('total_amount'))['total_amount__sum'] or 0
    total_approved_amount = approved_claims_obj.aggregate(Sum('amount'))['amount__sum'] or 0

    month_names = MONTH_NAMES

    context = {
        'current_year': current_year,
        'month_names': month_names,

        'pending_claims_count': pending_claims_count,
        'approved_claims_count': approved_claims_count,
        'rejected_claims_count': rejected_claims_count,

        'rejected_claims': rejected_claims,

        'total_pending_amount': total_pending_amount,
        'total_approved_amount': total_approved_amount,

        'pending_claims_by_month': pending_claims_by_month,
        'approved_claims_by_month': approved_claims_by_month,

        'total_pending_amount_by_month': total_pending_amount_by_month,
        'total_approved_amount_by_month': total_approved_amount_by_month,
    }
    
    return render(request, 'claim/claim_dashboard.html', context)

def claim_submit(request):
    if request.method == 'POST':
        form = ClaimForm(request.POST, request.FILES)
        if form.is_bound:  # Check if form is bound
            print("TEST")
            claim = form.save(commit=False)
            claim.claimer = request.user  # Set the claimer before validation
            form.instance = claim  # Update the form's instance

            if form.is_valid():
                try:
                    print("TEST2")
                    claim_status, created = Claim_Status.objects.get_or_create(status="Pending")
                    claim.claim_status = claim_status

                    # Amount Calculation
                    calculate_amounts(request.user, claim)
                
                    claim.save()
                    messages.success(request, 'Claim submitted successfully.')
                    return render(request, 'claim/claim_submit.html', {
                        "success": True})
                except ValidationError as e:
                    for error in e:
                        form.add_error(None, error)
    else:
        form = ClaimForm()

    context = {
        'form': form
    }

    return render(request, 'claim/claim_submit.html', context)

def claim_detail(request, claim_id):
    claim = Claim.objects.get(pk=claim_id)

    if request.user.id != claim.claimer.id and not request.user.is_staff and not request.user.groups.filter(name="Admin").exists():
        raise Http404("You are not authorized to access this file.")
    
    is_Pending = False
    is_Approved = False
    is_Rejected = False

    if claim.claim_status.id == 1:
        is_Pending = True
    elif claim.claim_status.id == 2:
        is_Approved = True
    else:
        is_Rejected = True

    approveForm = ApproveForm(prefix="approved")
    rejectForm = RejectForm(prefix="rejected")

    if request.method == 'POST':
        if 'approve' in request.POST:
            approveForm = ApproveForm(request.POST, request.FILES, prefix="approved")
            if approveForm.is_valid():
                instance = approveForm.save(commit=False)
                instance.claim = claim
                claim_status, created = Claim_Status.objects.get_or_create(status="Approved")
                claim.claim_status = claim_status
                claim.save()
                instance.save()
                return redirect('mitasa_admin:dashboard')
        elif 'reject' in request.POST:
            rejectForm = RejectForm(request.POST, prefix="rejected")
            if rejectForm.is_valid():
                instance = rejectForm.save(commit=False)
                instance.claim = claim
                claim_status, created = Claim_Status.objects.get_or_create(status="Rejected")
                claim.claim_status = claim_status
                claim.save()
                instance.save()
                return redirect('mitasa_admin:dashboard')
        else:
            approveForm = ApproveForm(prefix="approved")
            rejectForm = RejectForm(prefix="rejected")

    month_names = MONTH_NAMES
    accommodation_choice = ACCOMMODATION_CHOICE
    meal_choice = MEAL_CHOICE

    context = {
        'claim': claim,

        'month_names': month_names,
        'accommodation_choice': accommodation_choice,
        'meal_choice': meal_choice,

        'is_Pending': is_Pending,
        'is_Approved': is_Approved,
        'is_Rejected': is_Rejected,

        'approveForm': approveForm,
        'rejectForm': rejectForm,
    }
    
    return render(request, 'detail.html', context)

def claim_delete(request, claim_id):
    if request.method == 'POST':
        claim = Claim.objects.get(pk=claim_id)
        claim.delete()
    
    return HttpResponseRedirect(reverse('claim:dashboard'))

def claim_history(request):
    claims = Claim.objects.filter(claimer=request.user)

    claims_by_year_list = claims.values('claim_year').annotate(total_claims=Count('id')).annotate(total_approved_claims=Count('approved_claim__claim_id')).annotate(total_approved_amount=Sum('approved_claim__amount')).order_by('claim_year')

    overall_claims = 0
    overall_approved_claims = 0
    overall_approved_amount = 0

    for claim in claims_by_year_list:
        overall_claims += (claim['total_claims']) or 0
        overall_approved_claims += (claim['total_approved_claims']) or 0
        overall_approved_amount += (claim['total_approved_amount']) or 0

    context = {
        'claims_by_year_list': claims_by_year_list,

claim/templates/claim/claim_dashboard.html
{% extends "dashboard.html" %}
{% load static %}
{% block nav_claims %}
    active
{% endblock nav_claims %}
{% block page_title %}<span class="text-primary">Claim Dashboard</span> | {{ block.super }}{% endblock page_title %}
{% block history_link %}{% url 'claim:history' %}{% endblock history_link %}

claim/templates/claim/claim_history.html
{% extends "history.html" %}
{% block nav_claims %}
    active
{% endblock nav_claims %}
{% block page_title %}Claim History | {{ block.super }}{% endblock page_title %}

claim/templates/claim/claim_submit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block nav_claims %}
    active
{% endblock nav_claims %}
{% block content %}
    <div class="container mt-4">
        {% if success %}
            <div class="alert alert-success" role="alert">
                Claim filed successfully.
                <a href="{% url 'claim:dashboard' %}" class="alert-link">View claims.</a>
            </div>
        {% else %}
            <h1 class="text-center">Claim Submission Form</h1>
            <hr class="hr">
            <form action="{% url 'claim:submit' %}"
                method="post"
                enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Display non-field errors -->
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                            <br>
                        {% endfor %}
                    </div>
                {% endif %}
                <!-- Other form fields -->
                <input type="hidden" id="hidden_location" name="program_location" value="">
                <input type="hidden"
                    id="hidden_accommodation_choice"
                    name="accommodation_choice"
                    value="">
                <input type="hidden"
                    id="hidden_accommodation_amount"
                    name="accommodation_amount"
                    value="">
                <input type="hidden" id="hidden_meal_choice" name="meal_choice" value="">
                <input type="hidden" id="hidden_travel_amount" name="travel_amount" value="">
                <input type="hidden" id="hidden_toll_amount" name="toll_amount" value="">
                <input type="hidden"
                    id="hidden_parking_amount"
                    name="parking_amount"
                    value="">
                <input type="hidden"
                    id="hidden_plane_ticket_amount"
                    name="plane_ticket_amount"
                    value="">
                <input type="hidden" id="hidden_other_amount" name="other_amount" value="">
                <!-- Form fields go here -->
                <div class="d-flex flex-column">
                    <div class="form-floating mb-3">
                        {% render_field form.program_name placeholder="" class+="form-control" %}
                        <label for="id_program_name">Program Name</label>
                    </div>
                    <div class="form-floating flex-fill mb-3">
                        {% render_field form.program_mode placeholder="" class+="form-select" %}
                        <label for="id_program_mode">Program Mode</label>
                    </div>
                    <div class="form-floating mb-3">
                        {% render_field form.program_location placeholder="" class+="form-control" %}
                        <label for="id_program_location">Program Location</label>
                        <small class="form-text text-muted">If the program was online, please state 'Online'.</small>
                    </div>
                    <div class="form-floating flex-fill mb-3">
                        {% render_field form.accommodation_choice placeholder="" class+="form-select"%}
                        <label for="id_accommodation_choice">Accommodation</label>
                    </div>
                    <div class="d-flex flex-row flex-wrap justify-content-between">
                        <div class="form-floating me-2 mb-3">
                            {% render_field form.program_start_date placeholder="" class+="form-control" %}
                            <label for="id_program_start_date">Program Start Date</label>
                        </div>
                        <div class="form-floating me-2 mb-3">
                            {% render_field form.program_end_date placeholder="" class+="form-control" %}
                            <label for="id_program_end_date">Program End Date</label>
                        </div>
                        <div class="form-floating flex-fill me-2 mb-3">
                            {% render_field form.claim_month placeholder="" class+="form-select" %}
                            <label for="id_claim_month">Claim Month</label>
                        </div>
                        <div class="form-floating flex-fill mb-3">
                            {% render_field form.claim_year placeholder="" class+="form-control" %}
                            <label for="id_claim_year">Claim Year</label>
                        </div>
                    </div>
                    <div class="form-label bold-small">Program Letter:</div>
                    <div class="file-upload w-50 mb-3">{% render_field form.program_letter_file %}</div>
                    <hr class="hr">
                    <p class="lead">Please fill in the relevant fields only</p>
                    <!-- Meal-->
                    <div class="form-label bold-small">Meal:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50">{% render_field form.meal_choice placeholder="" class+="form-control" %}</div>
                    </div>
                    <!-- Accommodation-->
                    <div class="form-label bold-small mt-3">Accommodation:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50 me-2">
                            <span class="input-group-text">RM</span>
                            {% render_field form.accommodation_amount placeholder="" class+="form-control" min="0" %}
                        </div>
                        <div class="file-upload">{% render_field form.accommodation_file %}</div>
                    </div>
                    <!-- Travel -->
                    <div class="form-label bold-small mt-3">Mileage:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50 me-2">
                            {% render_field form.travel_distance placeholder="" class+="form-control" min="0" %}
                            <span class="input-group-text">KM</span>
                        </div>
                        <div class="file-upload">{% render_field form.travel_file %}</div>
                    </div>
                    <!-- Toll -->
                    <div class="form-label bold-small mt-3">Toll:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50 me-2">
                            <span class="input-group-text">RM</span>
                            {% render_field form.toll_amount placeholder="" class+="form-control" min="0" %}
                        </div>
                        <div class="file-upload">{% render_field form.toll_file %}</div>
                    </div>
                    <!-- Parking -->
                    <div class="form-label bold-small mt-3">Parking:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50 me-2">
                            <span class="input-group-text">RM</span>
                            {% render_field form.parking_amount placeholder="" class+="form-control" min="0" %}
                        </div>
                        <div class="file-upload">{% render_field form.parking_file %}</div>
                    </div>
                    <!-- Plane -->
                    <div class="form-label bold-small mt-3">Plane Ticket:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start">
                        <div class="input-group w-50 me-2">
                            <span class="input-group-text">RM</span>
                            {% render_field form.plane_ticket_amount placeholder="" class+="form-control" min="0"%}
                        </div>
                        <div class="file-upload">{% render_field form.plane_ticket_file %}</div>
                    </div>
                    <!-- Other -->
                    <div class="form-label bold-small mt-3">Others:</div>
                    <div class="d-flex flex-row flex-wrap justify-content-start mb-4">
                        <div class="input-group w-50 me-2">
                            <span class="input-group-text">RM</span>
                            {% render_field form.other_amount placeholder="" class+="form-control" min="0" %}
                        </div>
                        <div class="file-upload">{% render_field form.other_file %}</div>
                    </div>
                </div>
                <hr class="hr">
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        {% endif %}
    </div>
    {% include "claim/js/js.html" %}
{% endblock content %}

claim/templates/claim/history_dashboard.html
{% extends "dashboard.html" %}
{% block page_title %}<span class="text-danger">{{ year }} Claim History</span> | {{ block.super }}{% endblock page_title %}
{% block description %}
    <hr class="hr">
    <p class="lead">This is the claim archive for the year <span class="text-danger">{{ year }}</span></p>
{% endblock description %}
{% block button_1 %}<a class="btn btn-dark" href="{% url 'claim:history' %}" data-mdb-ripple-init data-mdb-ripple-color="dark">Back <i class="fas fa-arrow-left"></i></a>{% endblock button_1 %}
{% block button_2 %}{% endblock button_2 %}