mitasa/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from user.views import login_view as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', login, name='index'),
    path('', include('helper.urls')),
    path('user/', include('user.urls')),
    path('claim/', include('claim.urls')),
    path('staff/', include('mitasa_admin.urls')),
    path('medical/', include('medical_claim.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile_view, name="profile"),
    path('profile/new', views.profile_new, name="profile_new"),
    path('profile/edit', views.user_edit, name="edit"),
    path('profile/details/edit', views.profile_edit, name="profile_edit"),
    path('password/change', views.password_change, name="password_change"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

BANK_CHOICES = [
    ("Malayan Banking Berhad", "Malayan Banking Berhad"),
    ("CIMB Group Holdings", "CIMB Group Holdings"),
    ("Public Bank Berhad", "Public Bank Berhad"),
    ("RHB Bank", "RHB Bank"),
    ("Hong Leong Bank", "Hong Leong Bank"),
    ("AmBank", "AmBank"),
    ("UOB Malaysia", "UOB Malaysia"),
    ("Bank Rakyat", "Bank Rakyat"),
    ("OCBC Bank Malaysia", "OCBC Bank Malaysia"),
    ("HSBC Bank Malaysia", "HSBC Bank Malaysia"),
    ("Bank Islam Malaysia", "Bank Islam Malaysia"),
    ("Affin Bank", "Affin Bank"),
    ("Alliance Bank Malaysia Berhad", "Alliance Bank Malaysia Berhad"),
    ("Standard Chartered Bank Malaysia", "Standard Chartered Bank Malaysia"),
    ("MBSB Bank Berhad", "MBSB Bank Berhad"),
    ("Citibank Malaysia", "Citibank Malaysia"),
    ("Bank Simpanan Nasional (BSN)", "Bank Simpanan Nasional (BSN)"),
    ("Bank Muamalat Malaysia Berhad", "Bank Muamalat Malaysia Berhad"),
    ("Agrobank", "Agrobank"),
    ("Al-Rajhi Malaysia", "Al-Rajhi Malaysia"),
    ("Co-op Bank Pertama", "Co-op Bank Pertama"),
    ("MBSB Bank", "MBSB Bank")
    ]

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    bank_name = models.CharField(max_length=100, choices=BANK_CHOICES)
    account_number = models.CharField(max_length=18)
    phone_number = models.CharField(max_length=12, null=True, blank=True)

    def __str__(self):
        return f'{self.user.first_name}'

user/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["bank_name", "account_number", "phone_number"]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import Profile
from .forms import UserForm, ProfileForm
from django.contrib.auth.forms import PasswordChangeForm

# View Functions
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if request.user.is_staff:
                return redirect("index")
            else:
                return redirect("index")
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }
    return render(request, 'user/login/login.html', context)

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect("user:login")
    
@login_required(login_url='user:login')
def profile_view(request):
    context = {
        
    }  
    return render(request, 'user/profile/profile.html', context)

@login_required(login_url='user:login')
def profile_new(request):
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect("user:profile")
    else:
        form = ProfileForm()

    context = {
        'form': form
    }
    return render(request, 'user/profile/profile_edit.html', context)

@login_required(login_url='user:login')
def user_edit(request):
    if request.method == "POST":
        form = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("user:profile")
    else:
        form = UserForm(instance=request.user)

    context = {
        'form': form,
    }
    return render(request, 'user/profile/user_edit.html', context)

@login_required(login_url='user:login')
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("user:profile")
    else:
        form = ProfileForm(instance=profile)
    
    context = {
        'form': form,
    }
    return render(request, 'user/profile/profile_edit.html', context)

def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("user:profile")
    else:
        form = PasswordChangeForm(user=request.user)
    
    context = {
        'form': form,
    }
    return render(request, 'user/profile/password_change.html', context)

user/templates/user/profile/password_change.html
{% extends "user/profile/profile.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block password_change %}
    <form action="" method="post">
        {% csrf_token %}
        <label class="col-form-label bold-small">Old Password</label>
        {% render_field form.old_password class+="form-control" %}

        <label class="col-form-label bold-small">New Password</label>
        {% render_field form.new_password1 class+="form-control" %}

        <label class="col-form-label bold-small">Confirm New Password</label>
        {% render_field form.new_password2 class+="form-control" %}
        <div class="d-flex justify-content-end mt-3">
            <button type="submit" class="btn btn-primary me-2">Update</button>
            <a href="{% url 'user:profile' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
{% endblock password_change %}

user/templates/user/profile/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-4">
        {% include "user/alert/profile_alert.html" %}
        <!--User Information-->
        {% block profile %}
            <div class="d-flex flex-column justify-content-between">
                <div class="d-flex justify-content-between">
                    <h1>My Profile</h1>
                    <div class="align-self-center">
                        <a class="btn btn-secondary" href="{% url 'user:edit' %}">Update
                            <i class="fa-solid fa-pen-to-square fa-lg"></i>
                        </a>
                    </div>
                </div>
                <hr class="hr">
            </div>
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Username</label>
                <input class="form-control"
                       id="disabledInput"
                       type="text"
                       placeholder="{{ request.user.username }}"
                       disabled="">
            </fieldset>
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Name</label>
                <input class="form-control"
                       id="disabledInput"
                       type="text"
                       placeholder="{{ request.user.first_name }} {{ request.user.last_name }}"
                       disabled="">
            </fieldset>
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Email</label>
                <input class="form-control"
                       id="disabledInput"
                       type="text"
                       placeholder="{{ request.user.email }}"
                       disabled="">
            </fieldset>
            {% block password_change %}
            <a href="{% url 'user:password_change' %}">Change Password</a>
            {% endblock password_change %}
            <hr class="hr">
        {% endblock profile %}
        {% block bank %}
            <!--Bank Information-->
            <div class="d-flex justify-content-between mt-4">
                <h2>User Details</h2>
                <div class="align-self-center">
                    {% if request.user.profile %}
                        <a class="btn btn-secondary" href="{% url 'user:profile_edit' %}">Update
                            <i class="fa-solid fa-pen-to-square fa-lg"></i>
                        </a>
                    {% else %}
                        <a class="btn btn-secondary" href="{% url 'user:profile_new' %}">Update
                            <i class="fa-solid fa-pen-to-square fa-lg"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
            <hr class="hr">
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Bank</label>
                <input class="form-control"
                       id="disabledInput"
                       type="text"
                       placeholder="{{ request.user.profile.bank_name }}"
                       disabled="">
            </fieldset>
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Account Number</label>
                <input class="form-control"
                       id="disabledInput"
                       type="text"
                       placeholder="{{ request.user.profile.account_number }}"
                       disabled="">
            </fieldset>
            <fieldset class="mb-3" disabled="">
                <label class="form-label bold-small" for="disabledInput">Phone Number</label>
                <input class="form-control"
                    id="disabledInput"
                    type="text"
                    placeholder="{{ request.user.profile.phone_number }}"
                    disabled="">
            </fieldset>
        {% endblock bank %}
    </div>
{% endblock content %}

user/templates/user/profile/profile_edit.html
{% extends "user/profile/profile.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block bank %}
    <div class="d-flex justify-content-between">
        <h2>User Details</h2>
    </div>
    <hr class="hr">
    <div class="">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="col-form-label bold-small" for="inputDefault">Bank</label>
                {% render_field form.bank_name class+="form-select" %}
                <label class="col-form-label bold-small" for="inputDefault">Account Number</label>
                {% render_field form.account_number class+="form-control" %}
                <label class="col-form-label bold-small" for="inputDefault">Phone Number</label>
                {% render_field form.phone_number class+="form-control" %}
            </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary me-2">Update</button>
                <a href="{% url 'user:profile' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock bank %}

user/templates/user/profile/user_edit.html
{% extends "user/profile/profile.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block profile %}
    <div class="d-flex justify-content-between">
        <h1>My Profile</h1>
    </div>
    <hr class="hr">
    <fieldset class="mb-3" disabled="">
        <label class="form-label bold-small" for="disabledInput">Username</label>
        <input class="form-control"
               id="disabledInput"
               type="text"
               placeholder="{{ request.user.username }}"
               disabled="">
    </fieldset>
    <div class="">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label class="col-form-label bold-small" for="inputDefault">First Name</label>
                {% render_field form.first_name class+="form-control" %}
                <label class="col-form-label bold-small" for="inputDefault">Last Name</label>
                {% render_field form.last_name class+="form-control" %}
                <label class="col-form-label bold-small" for="inputDefault">Email</label>
                {% render_field form.email class+="form-control" %}
            </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary me-2">Update</button>
                <a href="{% url 'user:profile' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock profile %}