claim/urls.py
from django.urls import path
from . import views

app_name = "claim"

urlpatterns = [
    path('dashboard/', views.claim_dashboard, name="dashboard"),
    path('submit/', views.claim_submit, name="submit"),
    path('detail/<int:claim_id>', views.claim_detail, name="detail"),
    path('delete/<int:claim_id>', views.claim_delete, name="delete"),
    path('history/', views.claim_history, name="history"),
    path('history/<int:year>', views.history_dashboard, name="history_dashboard"),
]

medical_claim/urls.py
from django.urls import path
from . import views

app_name = "medical"

urlpatterns = [
    path('dashboard/', views.medical_dashboard, name='dashboard'),
    path('submit/', views.medical_submit, name='submit'),
    path('delete/<int:claim_id>', views.claim_delete, name='delete'),
    path('detail/<int:claim_id>', views.medical_detail, name='detail'),
    path('history/', views.medical_history, name='history'),
    path('history/<int:year>', views.medical_history_dashboard, name='history_dashboard'),
]

mitasa/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from user.views import login_view as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', login, name='index'),
    path('', include('helper.urls')),
    path('user/', include('user.urls')),
    path('claim/', include('claim.urls')),
    path('staff/', include('mitasa_admin.urls')),
    path('medical/', include('medical_claim.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mitasa_admin/urls.py
from django.urls import path
from . import views

app_name = "mitasa_admin"

urlpatterns = [
    path('dashboard/', views.admin_dashboard, name="dashboard"),
    path('history/', views.admin_history, name="history"),
    path('history/<int:year>', views.history_table, name="history_table"),
    path('user/<int:user_id>', views.user_dashboard, name="user_dashboard"),
    path('medical/dashboard/', views.medical_dashboard, name='medical_dashboard'),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile_view, name="profile"),
    path('profile/new', views.profile_new, name="profile_new"),
    path('profile/edit', views.user_edit, name="edit"),
    path('profile/details/edit', views.profile_edit, name="profile_edit"),
    path('password/change', views.password_change, name="password_change"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="en" id="htmlRoot" data-mdb-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MITASA Claim</title>
        {% include 'base/css.html' %}
    </head>
    <body>
        {% if request.user.is_authenticated %}
            <!-- Navbar -->
            <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-body-tertiary">
                <!-- Container wrapper -->
                <div class="container">
                    <!-- Toggle button -->
                    <button data-mdb-collapse-init
                            class="navbar-toggler"
                            type="button"
                            data-mdb-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <!-- Collapsible wrapper -->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Navbar brand -->
                        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'index' %}">MITASA</a>
                        <!-- Left links -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if request.user|has_group:"Admin" %}
                                <li class="nav-item dropdown">
                                    <a data-mdb-dropdown-init
                                    class="nav-link dropdown-toggle {% block nav_dashboard%}{% endblock nav_dashboard%}"
                                    href="#"
                                    id="navbarDropdownMenuLink"
                                    role="button"
                                    aria-expanded="false">Admin Dashboard</a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li>
                                            <a class="dropdown-item" href="{% url 'mitasa_admin:dashboard' %}">Claims</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'mitasa_admin:medical_dashboard' %}">Medical Claims</a>
                                        </li>
                                    </ul>
                                </li>
                            {% endif %}
                                <li class="nav-item dropdown">
                                    <a data-mdb-dropdown-init
                                    class="nav-link dropdown-toggle {% block nav_claims %}{% endblock nav_claims %}"
                                    href="#"
                                    id="navbarDropdownMenuLink"
                                    role="button"
                                    aria-expanded="false">Claims</a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <li>
                                            <a class="dropdown-item" href="{% url 'claim:dashboard' %}">Dashboard</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'claim:history' %}">Claim History</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'claim:submit' %}">Submit Claim</a>
                                        </li>
                                    </ul>
                                </li>
                            {% if request.user|has_group:"Staff" %}
                            <li class="nav-item">
                                <a class="nav-link {% block nav_medical_claims %}{% endblock nav_medical_claims %}"
                                   href="{% url 'medical:dashboard' %}">Medical Claims</a>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- Left links -->
                    </div>
                    <!-- Collapsible wrapper -->
                    <!-- Right elements -->
                    <div class="d-flex align-items-center">
                        <li class="nav-item align-items-center d-flex me-3">
                            <i class="fas fa-sun"></i>
                            <!-- Default switch -->
                            <div class="ms-2 form-check form-switch">
                                <input class="form-check-input"
                                       type="checkbox"
                                       role="switch"
                                       id="themingSwitcher" />
                            </div>
                            <i class="fas fa-moon"></i>
                        </li>
                        <div>
                            <a class="me-3">{{ request.user.first_name }}</a>
                        </div>
                        <!-- Icon -->
                        <!-- Avatar -->
                        <div class="dropdown">
                            <a data-mdb-dropdown-init
                               class="dropdown-toggle d-flex align-items-center hidden-arrow"
                               href="#"
                               id="navbarDropdownMenuAvatar"
                               role="button"
                               aria-expanded="false">
                                <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                                     class="rounded-circle"
                                     height="25"
                                     alt="Black and White Portrait of a Man"
                                     loading="lazy" />
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end"
                                aria-labelledby="navbarDropdownMenuAvatar">
                                <li>
                                    <a class="dropdown-item" href="{% url 'user:profile' %}">My profile</a>
                                </li>
                                {% if request.user.is_staff %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <form action="{% url 'user:logout' %}" method="post">
                                        {% csrf_token %}
                                        <button class="dropdown-item">Logout</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Right elements -->
                </div>
                <!-- Container wrapper -->
            </nav>
            <!-- Navbar -->
        {% else %}
            {% include 'nav/nav.html' %}
        {% endif %}
        {% block content %}
        {% endblock content %}
        {% include 'footer/footer.html' %}
        {% include 'base/js.html' %}
    </body>
</html>

templates/history.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-4">
        <h1>{% block page_title %}{{ request.user.first_name }}{% endblock page_title %}</h1>
        <hr class="hr">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <div class="align-self-center"><i class="fa-solid fa-list fa-lg"></i> List of Claims by Year</div>
                <div class="align-self-center"><a class="btn btn-dark" href="{% block back_link %}{% url 'claim:dashboard' %}{% endblock back_link %}">Back <i class="fas fa-arrow-left"></i></a></div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Year</th>
                                <th scope="col">Total Claims</th>
                                <th scope="col">Approved Claims</th>
                                <th scope="col">Approved Amount (RM)</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for claim in claims_by_year_list %}
                                <tr>
                                    <td>{{ claim.claim_year }}</td>
                                    <td>{{ claim.total_claims }}</td>
                                    <td>{{ claim.total_approved_claims }}</td>
                                    <td>{{ claim.total_approved_amount|default:"0" }}</td>
                                    <td>
                                        <a href="{% block view_link %}{% url 'claim:history_dashboard' claim.claim_year %}{% endblock view_link %}">View</a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td class="text-center" colspan="5">No claims found.</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td class="bold">Total</td>
                                <td>{{ overall_claims }}</td>
                                <td>{{ overall_approved_claims }}</td>
                                <td colspan="2">{{ overall_approved_amount }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/history_table.html
{% extends "dashboard.html" %}
{% block page_title %}<span class="text-warning">{{ year }} Claim History</span>{% endblock page_title %}
{% block card_1 %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-center text-primary">
                Total Claims <i class="fas fa-scroll"></i>
            </h5>
            <hr class="hr">
            <p class="card-text text-center lead">{{ claims|length }} Claims</p>
        </div>
    </div>
{% endblock card_1 %}
{% block card_2 %}{% endblock card_2 %}
{% block button_1 %}{% endblock button_1 %}
{% block dashboard_content %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between">
            <div class="form-control" data-mdb-input-init>
                <label class="form-label" for="nameFilter">Name</label>
                <input type="text" id="nameFilter" onkeyup="filterFunction()" class="form-control" />
            </div>
            <div class="form-select" data-mdb-input-init>
                <label class="form-label" for="monthFilter">Month</label>
                <select id="monthFilter" onchange="filterFunction()" class="form-control">
                    <option value="">All</option>
                    <option value="01">January</option>
                    <option value="02">February</option>
                    <option value="03">March</option>
                    <option value="04">April</option>
                    <option value="05">May</option>
                    <option value="06">June</option>
                    <option value="07">July</option>
                    <option value="08">August</option>
                    <option value="09">September</option>
                    <option value="10">October</option>
                    <option value="11">November</option>
                    <option value="12">December</option>
                </select>
            </div>
            <div class="form-select" data-mdb-input-init>
                <label class="form-label" for="statusFilter">Status</label>
                <select id="statusFilter" onchange="filterFunction()" class="form-control">
                    <option value="">All</option>
                    <option value="Pending">Pending</option>
                    <option value="Approved">Approved</option>
                    <option value="Rejected">Rejected</option>
                </select>
            </div>
        </div>
        <hr class="hr">
        <table class="table table-striped table-hover mt-2" id="myTable">
            <thead>
                <tr>
                    <th>Claim ID</th>
                    <th>Claimer</th>
                    <th>Program Name</th>
                    <th>Date</th>
                    <th>Amount (RM)</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for claim in claims  %}
                    <tr>
                        <td><a href="{% url 'claim:detail' claim.id %}"># {{ claim.id }}</a></td>
                        <td>{{ claim.claimer.first_name }}</td>
                        <td>{{ claim.program_name }}</td>
                        <td>{{ claim.created_at }}</td>
                        <td>
                            {% if claim.approved_claim %}
                                {{ claim.approved_claim.amount }}
                            {% else %}
                                {{ claim.total_amount }}
                            {% endif %}
                        </td>
                        <td>{{ claim.claim_status }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function filterFunction() {
            // Declare variables
            var nameInput, statusInput, monthInput, nameFilter, statusFilter, monthFilter, table, tr, td, i, nameTxtValue, statusTxtValue, dateTxtValue;
            nameInput = document.getElementById("nameFilter");
            statusInput = document.getElementById("statusFilter");
            monthInput = document.getElementById("monthFilter");
            nameFilter = nameInput.value.toUpperCase();
            statusFilter = statusInput.value.toUpperCase();
            monthFilter = monthInput.value;
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                nameTd = tr[i].getElementsByTagName("td")[1];
                statusTd = tr[i].getElementsByTagName("td")[5];
                dateTd = tr[i].getElementsByTagName("td")[3];
                if (nameTd && statusTd && dateTd) {
                    nameTxtValue = nameTd.textContent || nameTd.innerText;
                    statusTxtValue = statusTd.textContent || statusTd.innerText;
                    dateTxtValue = dateTd.textContent || dateTd.innerText;
                    var dateMonth = new Date(dateTxtValue).getMonth() + 1;
                    dateMonth = dateMonth < 10 ? '0' + dateMonth : dateMonth.toString();
                    if (nameTxtValue.toUpperCase().indexOf(nameFilter) > -1 && 
                        (statusFilter === "" || statusTxtValue.toUpperCase() === statusFilter) &&
                        (monthFilter === "" || dateMonth === monthFilter)) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock dashboard_content %}